title: Janhavi Sathe

description: >- # this means to ignore newlines until "baseurl:"
  2025 Janhavi Sathe
baseurl: "" # the subpath of your site, e.g. blog
url: "https://janhavi-sathe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  janhavi-sathe

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Theme-specific settings
minima:
  skin: auto
  header_pages:
    - posts.md
    - about.md
  # generate social links in footer
  social_links:
    github: janhavi-sathe
    linkedin: janhavi-sathe

# Author settings
author:
  name: Janhavi Sathe

# Show excerpts on the home page
show_excerpts: false

# Excerpt settings
excerpt_separator: "<!--more-->"  # Define a custom excerpt separator

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _pages
  - .htaccess