theme: minima
plugins:
  - jekyll-feed
#  - jekyll-remote-theme # add this line to the plugins list if you already have one
minima:
  skin: auto

  nav_pages:
    - posts.md
    - about.md

title: Janhavi Sathe

author:
  name: Janhavi Sathe

description: >- # this means to ignore newlines until "baseurl:"
  © Janhavi Sathe, 2025.

github_username: janhavi-sathe

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://janhavi-sathe.github.io" # the base hostname & protocol for your site, e.g. http://example.com

include:
  - _pages
  - .htaccess



show_excerpts: false